# Generated by Django 3.0.5 on 2020-10-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('oper', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('issuekey', models.CharField(max_length=100)),
                ('taskno', models.CharField(default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_trigger_record',
            },
        ),
    ]
