# Generated by Django 3.0.5 on 2020-10-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='inuse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
