# Generated by Django 3.0.5 on 2020-10-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_log_celerytaskid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='celerytaskid',
            new_name='celerytask_id',
        ),
    ]
