# Generated by Django 3.0.5 on 2020-10-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20201019_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='complete_at',
            field=models.DateTimeField(default='2020-10-16 15:07:03.547974'),
            preserve_default=False,
        ),
    ]
