# Generated by Django 3.0.5 on 2020-10-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_log_complete_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='complete_at',
        ),
    ]
