# Generated by Django 3.0.5 on 2020-10-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_log_complete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='complete_at',
            field=models.DateTimeField(default='2020-10-16 15:07:03.547974'),
        ),
    ]
