# Generated by Django 3.0.5 on 2020-10-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20201020_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='complete_at',
            field=models.DateTimeField(default='1997-10-16 15:07:03.547974'),
        ),
    ]
