# Generated by Django 3.0.5 on 2020-10-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20201022_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='celerytask_id',
            new_name='taskno',
        ),
        migrations.RemoveField(
            model_name='log',
            name='complete_at',
        ),
    ]
