# Generated by Django 3.0.5 on 2020-11-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20201030_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='time_cost',
            new_name='duration',
        ),
    ]
