# Generated by Django 3.0.5 on 2020-11-02 16:58

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20201102_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='envs',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
