# Generated by Django 3.0.5 on 2020-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_type', models.CharField(blank=True, max_length=50, null=True)),
                ('repo_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='仓库地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_app',
            },
        ),
    ]
