# Generated by Django 3.0.5 on 2020-09-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktsauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
