# Generated by Django 3.0.5 on 2020-09-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.IntegerField()),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('download_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='下载地址')),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='app.App')),
            ],
            options={
                'db_table': 't_artifact',
            },
        ),
    ]
