# Generated by Django 3.0.5 on 2020-09-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('config_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='app.App')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='server.Server')),
            ],
            options={
                'db_table': 't_service',
            },
        ),
    ]
